# --- Build Stage ---
FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /telegram_bot ./cmd/telegram_bot

# --- Final Stage ---
FROM alpine:latest

COPY --from=builder /telegram_bot /telegram_bot

ENTRYPOINT ["/telegram_bot"]
