version: "3.8"

services:
    auth-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - CONFIG_PATH=./configs/config.yml
        env_file:
            - .env
        networks:
            - auth_net
        restart: unless-stopped

    telegram-bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        depends_on:
            - auth-service
        environment:
            - AUTH_SERVICE_URL=http://auth-service:8080
        env_file:
            - .env
        networks:
            - auth_net
        restart: unless-stopped

networks:
    auth_net:
        driver: bridge
